name    'erwbgy-jboss'
version '0.1.0'
source 'https://github.com/erwbgy/puppet-jboss.git'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'Install and run JBoss products'
description 'Install and run JBoss products'
project_page 'git.com:erwbgy/puppet-jboss.git'
dependency 'erwbgy/runit', '>= 0.2.1'
